#!/usr/bin/env bash

# Syntax :
# -

source functions_personal

# Set the list of target directories for the back-up through their environment variable name
declare -a ARRAY_DIR_LIST_FOR_BACK_UP
ARRAY_DIR_LIST_FOR_BACK_UP+=("DIR_BACK_UP_PROFILES")
ARRAY_DIR_LIST_FOR_BACK_UP+=("DIR_BACK_UP_SYSTEM_CONFIG")
ARRAY_DIR_LIST_FOR_BACK_UP+=("DIR_BACK_UP_CHANNELS")
ARRAY_DIR_LIST_FOR_BACK_UP+=("DIR_BACK_UP_MANIFESTS")

# Set the list of profile files to back-up through their environment variable name
declare -a ARRAY_ENV_VAR_PROFILES_FILES
ARRAY_ENV_VAR_PROFILES_FILES+=("BASH_PROFILE")
ARRAY_ENV_VAR_PROFILES_FILES+=("BASHRC")
ARRAY_ENV_VAR_PROFILES_FILES+=("EMACS_CONF")
ARRAY_ENV_VAR_PROFILES_FILES+=("GIT_CONF")
ARRAY_ENV_VAR_PROFILES_FILES+=("PROXYCHAINS_CONF")
ARRAY_ENV_VAR_PROFILES_FILES+=("RBW_CONF")

# Path for external disks and output file
MAIN_EXTERNAL_DISK="${USB_CONNEXION_PATH}/Elements"
BACK_UP_EXTERNAL_DISK="${USB_CONNEXION_PATH}/Double"
SCRIPT_OUTPUT_FILE="${REPERTOIRE_TEMPORAIRE}/output.txt"
# Will enable the user to read the message before running a long command of back-up with external disk
PAUSE_BEFORE_RUN=5 

# Check that all back-up directories exist
for i in "${!ARRAY_DIR_LIST_FOR_BACK_UP[@]}"
do
    if [ ! -d "${!ARRAY_DIR_LIST_FOR_BACK_UP[$i]}" ]
    then
        # Exit with error else
	STDERR_show_message "\nERROR : the variable for the back-up directory \"${ARRAY_DIR_LIST_FOR_BACK_UP[$i]}\" is not correctly set. Currently, its value is \"${!ARRAY_DIR_LIST_FOR_BACK_UP[$i]}\" which is not a directory.\n"
        exit 1
    fi
done

# Back-up of profiles files
for i in "${!ARRAY_ENV_VAR_PROFILES_FILES[@]}"
do
    # Check that the file exists through its environment variable value
    if [ ! -f "${!ARRAY_ENV_VAR_PROFILES_FILES[$i]}" ]
    then
	# Exit with error else
	STDERR_show_message "\nERROR : The environment variable \"${ARRAY_ENV_VAR_PROFILES_FILES[$i]}\" is not correctly set. Currently, its value is \"${!ARRAY_ENV_VAR_PROFILES_FILES[$i]}\" which is not a file.\n"
	  exit 1
    fi

    # Back-up with confirmation of success / error through another script
    back_up_files_to_dir_with_timestamp -f  "${!ARRAY_ENV_VAR_PROFILES_FILES[$i]}" -d "$DIR_BACK_UP_PROFILES" ||
	exit 1

done

# Back-up of system configuration
# Check that the file exists
if [ ! -f "$GUIX_SYSTEM_CONF" ]
then
    # Exit with error else
    STDERR_show_message "\nERROR : The environment variable \"GUIX_SYSTEM_CONF\" is not correctly set. Currently, its value is \"$GUIX_SYSTEM_CONF\" which is not a file.\n"
      exit 1
else
# Back-up with confirmation of success / error through another script
back_up_files_to_dir_with_timestamp -f  "$GUIX_SYSTEM_CONF" -d "$DIR_BACK_UP_SYSTEM_CONFIG" ||
    exit 1
fi

# Back-up of channels configuration
# Check that the file exists
if [ ! -f "$GUIX_CHANNELS_CONF" ]
then
    # Exit with error else
    STDERR_show_message "\nERROR : The environment variable \"GUIX_CHANNELS_CONF\" is not correctly set. Currently, its value is \"$GUIX_CHANNELS_CONF\" which is not a file.\n"
      exit 1
else
# Back-up with confirmation of success / error through another script
back_up_files_to_dir_with_timestamp -f  "$GUIX_CHANNELS_CONF" -d "$DIR_BACK_UP_CHANNELS" ||
    exit 1
fi

# Back-up of current packages list
# Check if the file exists (it is a symlink) so not using '-f'
if [ ! -e "$GUIX_PACKAGES_INSTALLATION_PROFILE" ]
then
    # Exit with error else
    STDERR_show_message "\nERROR : The environment variable \"GUIX_PACKAGES_INSTALLATION_PROFILE\" is not correctly set. Currently, its value is \"$GUIX_PACKAGES_INSTALLATION_PROFILE\" which does not exist.\n"
      exit 1
else
    # Back-up with confirmation of success / error
    {  BACK_UP_MANIFEST_PATH="${DIR_BACK_UP_MANIFESTS}/$(timestamp_current)-manifest.scm" &&
	# Write a new file with the manifest of current packages.
	guix package -p "$GUIX_PACKAGES_INSTALLATION_PROFILE" --export-manifest > "$BACK_UP_MANIFEST_PATH" &&
      echo -e "\nOK - The manifest of current packages was saved under the path \"$BACK_UP_MANIFEST_PATH\".\n"
    }||
    { STDERR_show_message "\nERROR : The manifest of current packages could not be backed-up. Check script output and/or the back-up script.\n"
      exit 1
    }
fi

: <<"DISKPARTITIONINDEV"
# Back-up of disk-partition, size and filesystem types
#        - 'lsblk' to get the list of partitions as well as their sizes.
#	- 'lsblk -f' to get the filesystem types of the partitions
DISKPARTITIONINDEV




: <<"GITPARTINDEV"

# TO BE DONE LATER

# See the detailed list of steps in the back_up_checklist file (some were added).

# Git
# Ask if the development environment were saved
# If yes, then push all directories
# Ask the user to check git login space to check that the git push were well done.
# Only after this all, remove all git directories

# Require to remove the token

# List here the required git repository to clone in the development environment AND whether or not they are mine (to add the token)
# Require for the news token
# Clone the git dirs with urls provided and the token before if they are mine > can check it by greping the url to see if it contains my github name

GITPARTINDEV

# Purge local Bitwarden database (tool 'rbw')
{ rbw purge &&
  echo -e "\nOK : The local Bitwarden database was sucessfully purged.\n"
} ||
{    STDERR_show_message "\nERROR : The local Bitwarden database could not be purged. Check script output and/or do it manually...\n"
     exit 1
}

# Ask HERE the user to connect both disk OR exit if wished
# Check first if main external disk is connected - because some steps does not need secondary disk
# Then after, those, check if secondary disk is connected for the steps requiring it.

# Back-up of external disk
# Check if env var are okay and if the external disks are connected - else exit with error
if [[ ! -d "$MAIN_EXTERNAL_DISK" || ! -d "$BACK_UP_EXTERNAL_DISK" || ! -d "$REPERTOIRE_TEMPORAIRE" ]]
then
    echo -e "\nERROR : one (or more) of those var below is not correctly defined."
    echo -e "MAIN_EXTERNAL_DISK = \"$MAIN_EXTERNAL_DISK\""
    echo -e "BACK_UP_EXTERNAL_DISK = \"$BACK_UP_EXTERNAL_DISK\""
    echo -e "SCRIPT_OUTPUT_FILE = \"$SCRIPT_OUTPUT_FILE\""
    
    echo -e "Its is maybe because of the env var below :"
    echo -e "USB_CONNEXION_PATH = \"$USB_CONNEXION_PATH\""
    echo -e "REPERTOIRE_TEMPORAIRE = \"$REPERTOIRE_TEMPORAIRE\""
    echo "" # Esthetic
    exit 1
fi

# Remove content if file existing
echo -n "" > "$SCRIPT_OUTPUT_FILE"

# The below part will be set as optional

: <<"GITBACKUPINTOEXTERNALDISK"
# Copy all my git repo to main external disk : back-up in case GitHub server crash.
GITBACKUPINTOEXTERNALDISK

# The below part will be set as optional
: <<"OPTIONALHOMEBACKUPINDEV"

# Optional back-up of home
COMMAND="sudo back_up_a_dir_to_another -s $HOME -d ${MAIN_EXTERNAL_DISK}/home "
echo "$COMMAND"

# Show the current step
echo -e "\nBacking-up the \"home\" directory into the main external disk...\n" &&
# Pause X seconds to let the user read the message
sleep $PAUSE_BEFORE_RUN

# Back-up
{ $COMMAND &&
      echo "OK - COMMAND \"$COMMAND\"" >> "$SCRIPT_OUTPUT_FILE"
} || echo "ERROR - COMMAND \"$COMMAND\"" >> "$SCRIPT_OUTPUT_FILE"
echo -e "\n\n" >> "$SCRIPT_OUTPUT_FILE" # Esthetic

OPTIONALHOMEBACKUPINDEV

# The below part will be set as optional
: <<"SETOPTIONALHEREINDEV"
SETOPTIONALHEREINDEV

# Back-up of main external disk to secondary one
COMMAND="sudo back_up_a_dir_to_another -s ${MAIN_EXTERNAL_DISK}/ -d ${BACK_UP_EXTERNAL_DISK} "

# Show the current step
echo -e "\nBacking-up the main external disk to the secondary one...\n" &&
# Pause X seconds to let the user read the message
sleep $PAUSE_BEFORE_RUN

# Back-up
{ $COMMAND &&
      echo "OK - COMMAND \"$COMMAND\"" >> "$SCRIPT_OUTPUT_FILE"
} || echo "ERROR - COMMAND \"$COMMAND\"" >> "$SCRIPT_OUTPUT_FILE"
echo -e "\n\n" >> "$SCRIPT_OUTPUT_FILE" # Esthetic

# Showing the results
echo -e "\nBack-up of external disks finished - Please check the results.\n"
file_open -f "$SCRIPT_OUTPUT_FILE"
