#!/usr/bin/env bash

source fonctions_personnelles

# Syntaxe :
SYNTAXE="$(syntaxe_afficher_si_erreur "$(basename $0)" "-u URL" "[-b BALISE_HTML]" "[-c COMPLEMENT_PR_PUP]" )"
# Fonctionnement
# Retourne les balises recherchées et leur contenu

# Contrôle des arguments
FLAG_OPTION_U=
FLAG_OPTION_B=
FLAG_OPTION_C=
while getopts ':u:b:c:' OPTION # le résultat de getopts à chaque boucle est stocké dans $OPTION
do
    case $OPTION in
        u )     FLAG_OPTION_U=1
                URL="$OPTARG"
                # Test si url existe
                if [ $(url_test_si_existe -u "$URL" ) -eq 0 ]
                then
                    :
                else
                    STDERR_afficher_message "\nERROR : L'url \"$URL\" n'existe pas.\n"
                    STDERR_afficher_message "$SYNTAXE"
                    exit 1
                fi
                ;;
        b )     FLAG_OPTION_B=1
                BALISE_HTML="$OPTARG"
                ;;
        c )     FLAG_OPTION_C=1     
                COMPLEMENT_PR_PUP="$OPTARG"
                ;;
        # Argument manquant
        \: )    STDERR_afficher_message "\nERROR : Argument manquant pour l'option -$OPTARG.\n" # les ':'' signifie que la valeur de l'argument n'a pas été trouvée = argument manquant
                STDERR_afficher_message "$SYNTAXE"
                exit 2
                ;;
        # Option inconnue
        \? )    STDERR_afficher_message "ERROR : Option inconnue : -$OPTARG\n"
                STDERR_afficher_message "$SYNTAXE"
                exit 3
                ;;
    esac
done
shift $(($OPTIND - 1)) # décalage en supprimant les options acquises

# Test si l'option F a été fourni (=test si flag défini)
if [ ! -z "$FLAG_OPTION_U" ]
then
    # Test si d'autres darguments = en trop (=test si $1 défini)
    if [ ! -z "$1" ]
    then
        STDERR_afficher_message "\nERROR : argument(s) en trop : \"$*\".\n"
        STDERR_afficher_message "$SYNTAXE"
        exit 4 
    else
        :
    fi
else
    STDERR_afficher_message "\nERROR : Vous devez fournir l'option -u avec son argument.\n"
    STDERR_afficher_message "$SYNTAXE"
    exit 5 
fi

# Affichage du résultat avec mise en couleur pour une meilleure clarté
# Si aucune balise transmise alors affichage de toutes les balises
if [ -z "$FLAG_OPTION_B" ]
then
    curl -s "$URL" | pup --color
else # Sinon affichage de la balise en question
    # S'il n'y a pas de complément
    if [ -z "$FLAG_OPTION_C" ]
    then
        # Affichage de la balise
        curl -s "$URL" | pup --color "$BALISE_HTML"
    else # Sinon requête balise + complément pour pup
        curl -s "$URL" | pup --color "$BALISE_HTML $COMPLEMENT_PR_PUP"
    fi
fi

