#!/usr/bin/env bash

source fonctions_personnelles

# Syntaxe
SYNTAXE="$(syntaxe_afficher_si_erreur "$(basename $0)" "-u URL" )"
# Coeur du script copié ici : https://www.cyberciti.biz/faq/get-extract-domain-name-from-url-in-linux-unix-bash/

# Contrôle des arguments
FLAG_OPTION_U= # non défini par défaut pr test après lecture des options
while getopts ':u:' OPTION # le résultat de getopts à chaque boucle est stocké dans $OPTION
do
    case $OPTION in
        u )     FLAG_OPTION_U=1
                URL="$OPTARG"
                # Test si url existe
                if [ $(url_test_si_existe -u "$URL" ) -eq 0 ]
                then
                    :
                else
                    STDERR_afficher_message "\nERROR : L'url \"$URL\" n'existe pas ou est déviée.\n"
                    STDERR_afficher_message "$SYNTAXE"
                    exit 1
                fi
                ;;
        # Argument manquant
        \: )    STDERR_afficher_message "\nERROR : Argument manquant pour l'option -$OPTARG.\n" # les ':'' signifie que la valeur de l'argument n'a pas été trouvée = argument manquant
                STDERR_afficher_message "$SYNTAXE"
                exit 2
                ;;
        # Option inconnue
        \? )    STDERR_afficher_message "ERROR : Option inconnue : -$OPTARG\n"
                STDERR_afficher_message "$SYNTAXE"
                exit 3
                ;;
    esac
done
shift $(($OPTIND - 1)) # décalage en supprimant les options acquises

# Test si l'option F a été fourni (=test si flag défini)
if [ ! -z "$FLAG_OPTION_U" ]
then
    # Test si d'autres darguments = en trop (=test si $1 défini)
    if [ ! -z "$1" ]
    then
        STDERR_afficher_message "\nERROR : argument(s) en trop : \"$*\".\n"
        STDERR_afficher_message "$SYNTAXE"
        exit 4 
    else
        :
    fi
else
    STDERR_afficher_message "\nERROR : Vous devez fournir les arguments -u avec son argument.\n"
    STDERR_afficher_message "$SYNTAXE"
    exit 5 
fi

## Remove protocol part of url  ##
URL="${URL#http://}"
URL="${URL#https://}"
URL="${URL#URLtp://}"
URL="${URL#scp://}"
URL="${URL#scp://}"
URL="${URL#sURLtp://}"

## Remove username and/or username:password part of URL  ##
URL="${URL#*:*@}"
URL="${URL#*@}"
 
## Remove rest of urls ## dont le dernier slash
URL=${URL%%/*}

## Show domain name only ##
echo "$URL"