#!/usr/bin/env bash

# Script bidon test
# Peut être effacé
SOMME_TOTALE=0;
while read NOMBRE
do
	echo "NOMBRE : $NOMBRE"
	SOMME_TOTALE=$((SOMME_TOTALE + NOMBRE))
	echo "SOMME : $SOMME_TOTALE"
done < <(mount |
       	       awk ' { for (i=1; i<NF; i++) \
	       { if ( $i ~ /\/.*/ ) \
	       {printf("%s\n", $i) }
	       }
	       }' |
	       sort -u |
	       xargs -n 1 df |
	       grep -v 'Sys. de fichiers' |
	       grep -v 'none' |
	       awk ' { print $2 } ' |
	       grep -E -v '^0$')
	 

