#!/usr/bin/env bash

# Syntaxe :
# - : pas d'argument à fournir

source fonctions_personnelles

COMMANDE="${0##*/}" # nom de la commande utile pour les messages d'erreur

# Execute some actions before shutting down.
turn_off_actions_before ||
    { STDERR_show_message "\nERROR : could not process all required actions before shutting down.\n Please check output...\n" &&
      exit 1
    }

# Redémarrer l'ordinateur
echo -e "\nSaisissez votre mot de passe et l'ordinateur redémarrera IMMEDIATEMENT."
echo -e "Annulez avec CTRL+C\n"
sudo shutdown -r now ||
{ echo -e "\nERREUR : la commande \"$COMMANDE\" a échoué.\n" ; exit 1 ; }
