#!/usr/bin/env bash

# Syntaxe :
# $1 : index of the command from select menu to run (optionnel)

# Get the list of all my personal commands
declare -a LISTE_COMMANDE
OPTION_SORTIE="Quitter"
for command in $REPERTOIRE_DES_COMMANDES_PERSO/*
do
    command=${command#$REPERTOIRE_DES_COMMANDES_PERSO}
    command=${command#\/}
    LISTE_COMMANDE+=("$command")
done

# Sort array elements
STRING_LISTE_TRIEE_COMMANDES="$( tr ' ' '\n' <<<"${LISTE_COMMANDE[*]}" | sort --ignore-case | tr '\n' ' ' )"
# '<<<' : Transformation du string en un fichier (temporaire)
# tr : remplacement des espaces ' ' par un retour à la ligne '\n'
# sort --ignore-case : tri dans l'ordre alphabétique en ignorant la casse
# tr : remplacement des retour à la ligne par des espaces

# Convert string to array in order to enable looping on them
LISTE_COMMANDE=($STRING_LISTE_TRIEE_COMMANDES) 

# Add the option to quit
LISTE_COMMANDE+=("$OPTION_SORTIE") 
DERNIERE_OPTION=${#LISTE_COMMANDE[@]}

# Select command to run - also option to quit
CHOIX=""

# Argument provided processing if any (comand to run = index-1)
if [ -z "$1" ]
then
    :
else
    if [[ $1 -gt 0 && $1 -le $DERNIERE_OPTION ]] # si choix compris dans la liste // -gt = greater than // -le = less than or equal to
    then
        index=$(($1-1)) # car les choix sélect débute à 1 et l'index à 0
        CHOIX="${LISTE_COMMANDE[$index]}"
    else
        echo -e "\nERREUR : votre saisie \"$1\" ne fait pas partie de la liste de choix.\nTapez \"$DERNIERE_OPTION\" pour \"$OPTION_SORTIE\""
    fi
fi

# Loop as long as the user does not make a correct choice. As long as it is not a string with > 1 char
until [ -n "$CHOIX" ] 
do
    echo -e "\nChoisissez une commande pour l'exécuter ou tapez \"$DERNIERE_OPTION\" pour \"$OPTION_SORTIE\"\n"
    select CHOIX in "${LISTE_COMMANDE[@]}"
    do
        break 
    done
    # Check if choice is incorrect
    if [ ! -n "$CHOIX" ]
    then
        echo -e "ERREUR : votre saisie ne fait pas partie de la liste de choix.\nTapez \"$DERNIERE_OPTION\" pour \"$OPTION_SORTIE\""
    fi
done    

if [ "$CHOIX" == "$OPTION_SORTIE" ]
then
    echo -e "\nVous avez choisi de \"$CHOIX\" sans exécuter de commande.\n"
    exit 0
else
    echo -e "\nExécution de la commande \"$CHOIX\"\n"
    exec $CHOIX ||
    { echo -e "\nERREUR : la commande \"$CHOIX\" n'a pas fonctionné.\n" ; exit 1 ; }
fi
