#!/usr/bin/env bash

source functions_personal

COUNTER=0
MESSAGE_SHOWING_NOTHING_TO_COMMIT="nothing to commit, working tree clean"
MESSAGE_SHOWING_NOTHING_TO_PUSH="Your branch is up to date with"
declare -a DIRECTORY_TO_COMMIT_LIST
declare -a DIRECTORY_TO_PUSH_LIST

while read DEVELOPMENT_DIRECTORY
do

	OLDPWD="$PWD"
	cd "$DEVELOPMENT_DIRECTORY"
	# Test if the directory has to be commit. If so, grep does not return an exit code of 0.
        git status | grep "$MESSAGE_SHOWING_NOTHING_TO_COMMIT" >/dev/null 2>&1
	if (($?))
	then
	    DIRECTORY_TO_COMMIT_LIST+=("$DEVELOPMENT_DIRECTORY")
        else
	    git status | grep "$MESSAGE_SHOWING_NOTHING_TO_PUSH" >/dev/null 2>&1
	    if (($?))
	    then
		DIRECTORY_TO_PUSH_LIST+=("$DEVELOPMENT_DIRECTORY")
	    fi
	fi
	cd "$OLDPWD"	
done < <(find "$REPERTOIRE_DEVELOPPEMENT" -mindepth 1 -maxdepth 1)

# Get the number of directories of each category
NUMBER_OF_DIRECTORY_TO_COMMIT=$(tableau_taille DIRECTORY_TO_COMMIT_LIST)
NUMBER_OF_DIRECTORY_TO_PUSH=$(tableau_taille DIRECTORY_TO_PUSH_LIST)

# Check if there is at least one directory in one category with an action to do.
if [[ $((NUMBER_OF_DIRECTORY_TO_COMMIT)) -gt 0 || $((NUMBER_OF_DIRECTORY_TO_PUSH)) -gt 0 ]]
then
    # If so, show message.
    echo -e "\nList of Git dirs: \n"
    
    # If at least one directory to be committed
    if [ $((NUMBER_OF_DIRECTORY_TO_COMMIT)) -gt 0 ]
    then
	# Get a sorted list of directories
        declare -a SORTED_DIRECTORY_TO_COMMIT_LIST
	tableau_trier_ordre_alphabetique_pas_numero DIRECTORY_TO_COMMIT_LIST SORTED_DIRECTORY_TO_COMMIT_LIST
        # And print them with their status
	for EACH_DIRECTORY in "${SORTED_DIRECTORY_TO_COMMIT_LIST[@]}"
	do
	    ((COUNTER++))
	    echo -e "$COUNTER - ${EACH_DIRECTORY##*/} - to be committed"
	done
    fi

    # If at least one directory to be pushed
    if [ $((NUMBER_OF_DIRECTORY_TO_PUSH)) -gt 0 ]
    then
	# Get a sorted list of directories
        declare -a SORTED_DIRECTORY_TO_PUSH_LIST
	tableau_trier_ordre_alphabetique_pas_numero DIRECTORY_TO_PUSH_LIST SORTED_DIRECTORY_TO_PUSH_LIST
        # And print them with their status
	for EACH_DIRECTORY in "${SORTED_DIRECTORY_TO_PUSH_LIST[@]}"
	do
	    ((COUNTER++))
	    echo -e "$COUNTER - ${EACH_DIRECTORY##*/} - to be pushed"
	done
    fi

    echo "" # Esthetic

else
    # Else, there is neither commits, nor pushes to do.
    # So show confirmation message.
    echo -e "\nAll Git dirs are up-to-date.\n"
fi

exit 0
