#!/usr/bin/env bash

# Syntaxe :
# - : pas d'argument à fournir

source functions_personal

COMMANDE="${0##*/}" # nom du fichier = utile pour les messages d'erreur

# Execute some actions before shutting down.
turn_off_actions_before ||
    { STDERR_show_message "\nERROR : could not process all required actions before the stand-by.\n Please check output...\n" &&
      exit 1
    }

# Ask user if agree to continue else, if 'sudo' is required for any of the commands called_before, it will process immediatly without possibility of stop this action.
ask_user_if_agree_to_continue

# Stand-by
echo -e "\nWrite your password and the computer will stand-by immediatly."
echo -e "Cancel with CTRL+C\n"
sudo herd halt shepherd ||
    { echo -e "\nERROR : the command \"$COMMAND\" failed.\n"
      exit 2
    }
