#!/usr/bin/env bash

# Syntaxe :
# - : pas d'argument à fournir

# Calling a few custom scripts
git_push_avant_deteindre_ordinateur || exit 1
corbeille_vider || exit 1
disque_dur_ejecter ||  exit 1

# The below script is still in dev so not run at the moment.
#bluetooth_eteindre || exit 1
