#!/usr/bin/env bash

# Syntaxe :
# - : pas d'argument à fournir

# Calling a few custom scripts
git_push_before_turn_off || exit 1
trashes_empty || exit 1
usb_drive_unmount ||  exit 1

# The below script is still in dev so not run at the moment.
#bluetooth_eteindre || exit 1
