#!/usr/bin/env bash

# Syntaxe :
# - : pas d'argument à fournir

source functions_personal

COMMAND="${0##*/}" # nom du fichier = utile pour les messages d'erreur

# Execute some actions before shutting down.
turn_off_actions_before ||
    { STDERR_afficher_message "\nERROR : could not process all required actions before shutting down.\n Please check output...\n" &&
      exit 1
    }

# Shutdown
echo -e "\nWrite your password and the computer will shutdown immediatly."
echo -e "Cancel with CTRL+C\n"
sudo herd power-off shepherd ||
    { echo -e "\nERROR : the command \"$COMMAND\" failed.\n"
      exit 2
    }
