#!/usr/bin/env bash

source fonctions_personnelles

URL_BRUTTE="https://comptedemoettests.pythonanywhere.com/"

curl -s "$URL_BRUTTE" | grep -E "<a href=[^>]*>" | sed -E 's/<a href="([^"]*)".*>/\1/' | sed "s/^[[:space:]]*//" |  sed "s/[[:space:]]*$//"



URL="${URL_BRUTTE%/}" # suppression du slash final s'il y a
REGEX_DEBUT_URL="http(s)?://(www\.)?"
#URL_PR_SED="$(echo "$URL" | sed -e "s/\//\\//g")"
URL_PR_SED="$(sed_preparation_pr_variable_utilisee_dans_sed_avec_slash_remplacement_en_antislash_slash "$URL" )"
#exit 0
curl -s "$URL" | grep -E "<a href=[^>]*>" | sed -E 's/<a href="([^"]*)".*>/\1/' | sed "s/^[[:space:]]*//" |  sed "s/[[:space:]]*$//" # | sed -e "s/^\//$URL_PR_SED\//" # | grep -o -E "$REGEX_DEBUT_URL.*\..*"